language: scala  # Die verwendete Programmiersprache

scala:
  - 3.4.1  # Die gewünschte Scala-Version



# Hier folgen die Build-Steps
script:
  - sbt clean test coverage


# Hier könnten weitere Konfigurationen folgen, wie z.B. Benachrichtigungen oder Deployment-Optionen
after-succes:
  - sbt coverageReport
