name: Scala CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: compile
        run: sbt compile
  run_tests:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - name: Build Project and export Coverage
       env:
         CODECOV_TOKEN: ${{ secrets.CONNECTFOUR_TOKEN }}
         COVERALLS_REPO_TOKEN: ${{ secrets.CONNECTFOUR_TOKEN }}
       run: |
         export CI_BRANCH="${GITHUB_REF#refs/heads/}"
         sbt clean jacocoCoveralls

